/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Betting } from "./Betting";
export type { Chess } from "./Chess";
export type { Leela } from "./Leela";
export * as factories from "./factories";
export { Betting__factory } from "./factories/Betting__factory";
export { Chess__factory } from "./factories/Chess__factory";
export { Leela__factory } from "./factories/Leela__factory";
