/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "BettingGame",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BettingGame__factory>;
    getContractFactory(
      name: "Chess",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Chess__factory>;
    getContractFactory(
      name: "ChessTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ChessTest__factory>;
    getContractFactory(
      name: "IChess",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IChess__factory>;
    getContractFactory(
      name: "Leela",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Leela__factory>;
    getContractFactory(
      name: "Hasher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Hasher__factory>;
    getContractFactory(
      name: "Validator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Validator__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "BettingGame",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BettingGame>;
    getContractAt(
      name: "Chess",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Chess>;
    getContractAt(
      name: "ChessTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ChessTest>;
    getContractAt(
      name: "IChess",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IChess>;
    getContractAt(
      name: "Leela",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Leela>;
    getContractAt(
      name: "Hasher",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Hasher>;
    getContractAt(
      name: "Validator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Validator>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
