/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { BettingGame } from "./contracts/betting.sol/BettingGame";
export { BettingGame__factory } from "./factories/contracts/betting.sol/BettingGame__factory";
export type { Chess } from "./contracts/chess.sol/Chess";
export { Chess__factory } from "./factories/contracts/chess.sol/Chess__factory";
export type { ChessTest } from "./contracts/ChessTest";
export { ChessTest__factory } from "./factories/contracts/ChessTest__factory";
export type { IChess } from "./contracts/IChess";
export { IChess__factory } from "./factories/contracts/IChess__factory";
export type { Leela } from "./contracts/leela.sol/Leela";
export { Leela__factory } from "./factories/contracts/leela.sol/Leela__factory";
export type { Hasher } from "./contracts/Validator.sol/Hasher";
export { Hasher__factory } from "./factories/contracts/Validator.sol/Hasher__factory";
export type { Validator } from "./contracts/Validator.sol/Validator";
export { Validator__factory } from "./factories/contracts/Validator.sol/Validator__factory";
