/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ChessTestInterface extends utils.Interface {
  functions: {
    "game_state()": FunctionFragment;
    "getGameState()": FunctionFragment;
    "movePawn()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "game_state" | "getGameState" | "movePawn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "game_state",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGameState",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "movePawn", values?: undefined): string;

  decodeFunctionResult(functionFragment: "game_state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "movePawn", data: BytesLike): Result;

  events: {};
}

export interface ChessTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ChessTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    game_state(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGameState(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { _game_state_array: BigNumber[] }>;

    movePawn(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  game_state(overrides?: CallOverrides): Promise<BigNumber>;

  getGameState(overrides?: CallOverrides): Promise<BigNumber[]>;

  movePawn(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    game_state(overrides?: CallOverrides): Promise<BigNumber>;

    getGameState(overrides?: CallOverrides): Promise<BigNumber[]>;

    movePawn(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    game_state(overrides?: CallOverrides): Promise<BigNumber>;

    getGameState(overrides?: CallOverrides): Promise<BigNumber>;

    movePawn(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    game_state(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGameState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    movePawn(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
