/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as validatorSol from "./Validator.sol";
export type { validatorSol };
import type * as bettingSol from "./betting.sol";
export type { bettingSol };
import type * as chessSol from "./chess.sol";
export type { chessSol };
import type * as leelaSol from "./leela.sol";
export type { leelaSol };
export type { ChessTest } from "./ChessTest";
export type { IChess } from "./IChess";
