import { ChessBoardData, ChessPiece } from '../../../types/Chess.type';

export const BOARD_0: ChessBoardData = [
  { chessPiece: ChessPiece.B_ROOK, column: 'A', row: 8 },
  { chessPiece: ChessPiece.B_KNIGHT, column: 'B', row: 8 },
  { chessPiece: ChessPiece.B_BISHOP, column: 'C', row: 8 },
  { chessPiece: ChessPiece.B_KING, column: 'D', row: 8 },
  { chessPiece: ChessPiece.B_QUEEN, column: 'E', row: 8 },
  { chessPiece: ChessPiece.B_BISHOP, column: 'F', row: 8 },
  { chessPiece: ChessPiece.B_KNIGHT, column: 'G', row: 8 },
  { chessPiece: ChessPiece.B_ROOK, column: 'H', row: 8 },
  { chessPiece: ChessPiece.B_PAWN, column: 'A', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'B', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'C', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'D', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'E', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'F', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'G', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'H', row: 7 },
  // ---
  { chessPiece: ChessPiece.W_ROOK, column: 'A', row: 1 },
  { chessPiece: ChessPiece.W_KNIGHT, column: 'B', row: 1 },
  { chessPiece: ChessPiece.W_BISHOP, column: 'C', row: 1 },
  { chessPiece: ChessPiece.W_KING, column: 'D', row: 1 },
  { chessPiece: ChessPiece.W_QUEEN, column: 'E', row: 1 },
  { chessPiece: ChessPiece.W_BISHOP, column: 'F', row: 1 },
  { chessPiece: ChessPiece.W_KNIGHT, column: 'G', row: 1 },
  { chessPiece: ChessPiece.W_ROOK, column: 'H', row: 1 },
  { chessPiece: ChessPiece.W_PAWN, column: 'A', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'B', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'C', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'D', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'E', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'F', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'G', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'H', row: 2 },
];

export const BOARD_1: ChessBoardData = [
  { chessPiece: ChessPiece.B_ROOK, column: 'A', row: 6 },
  { chessPiece: ChessPiece.B_KNIGHT, column: 'B', row: 5 },
  { chessPiece: ChessPiece.B_BISHOP, column: 'C', row: 8 },
  { chessPiece: ChessPiece.B_KING, column: 'D', row: 7 },
  { chessPiece: ChessPiece.B_QUEEN, column: 'E', row: 3 },
  { chessPiece: ChessPiece.B_BISHOP, column: 'F', row: 8 },
  { chessPiece: ChessPiece.B_KNIGHT, column: 'G', row: 6 },
  { chessPiece: ChessPiece.B_ROOK, column: 'H', row: 6 },
  { chessPiece: ChessPiece.B_PAWN, column: 'A', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'B', row: 6 },
  { chessPiece: ChessPiece.B_PAWN, column: 'C', row: 4 },
  { chessPiece: ChessPiece.B_PAWN, column: 'D', row: 4 },
  { chessPiece: ChessPiece.B_PAWN, column: 'E', row: 5 },
  { chessPiece: ChessPiece.B_PAWN, column: 'F', row: 6 },
  { chessPiece: ChessPiece.B_PAWN, column: 'G', row: 7 },
  { chessPiece: ChessPiece.B_PAWN, column: 'H', row: 7 },
  // ---
  { chessPiece: ChessPiece.W_ROOK, column: 'A', row: 4 },
  { chessPiece: ChessPiece.W_KNIGHT, column: 'B', row: 5 },
  { chessPiece: ChessPiece.W_BISHOP, column: 'C', row: 1 },
  { chessPiece: ChessPiece.W_KING, column: 'D', row: 2 },
  { chessPiece: ChessPiece.W_QUEEN, column: 'E', row: 4 },
  { chessPiece: ChessPiece.W_BISHOP, column: 'F', row: 3 },
  { chessPiece: ChessPiece.W_KNIGHT, column: 'G', row: 5 },
  { chessPiece: ChessPiece.W_ROOK, column: 'H', row: 6 },
  { chessPiece: ChessPiece.W_PAWN, column: 'A', row: 7 },
  { chessPiece: ChessPiece.W_PAWN, column: 'B', row: 6 },
  { chessPiece: ChessPiece.W_PAWN, column: 'C', row: 5 },
  { chessPiece: ChessPiece.W_PAWN, column: 'D', row: 4 },
  { chessPiece: ChessPiece.W_PAWN, column: 'E', row: 2 },
  { chessPiece: ChessPiece.W_PAWN, column: 'F', row: 5 },
  { chessPiece: ChessPiece.W_PAWN, column: 'G', row: 6 },
  { chessPiece: ChessPiece.W_PAWN, column: 'H', row: 7 },
];
