/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as validatorSol from "./Validator.sol";
export * as bettingSol from "./betting.sol";
export * as chessSol from "./chess.sol";
export * as leelaSol from "./leela.sol";
export { ChessTest__factory } from "./ChessTest__factory";
export { IChess__factory } from "./IChess__factory";
