/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ChessInterface extends utils.Interface {
  functions: {
    "betting()": FunctionFragment;
    "blackState()": FunctionFragment;
    "boardState()": FunctionFragment;
    "checkBishopValidMoves(uint256,uint8,uint32)": FunctionFragment;
    "checkEndgame()": FunctionFragment;
    "checkForCheck(uint256,uint32)": FunctionFragment;
    "checkKingValidMoves(uint256,uint8,uint32)": FunctionFragment;
    "checkKnightValidMoves(uint256,uint8,uint32)": FunctionFragment;
    "checkMove(uint16)": FunctionFragment;
    "checkPawnValidMoves(uint256,uint8,uint32,uint32)": FunctionFragment;
    "checkQueenValidMoves(uint256,uint8,uint32)": FunctionFragment;
    "checkRookValidMoves(uint256,uint8,uint32)": FunctionFragment;
    "commitMove(uint256,uint8,uint8)": FunctionFragment;
    "convertToCircuit()": FunctionFragment;
    "currentTurnBlack()": FunctionFragment;
    "gameIndex()": FunctionFragment;
    "gameStateLists(uint16,uint256)": FunctionFragment;
    "getChessGameState()": FunctionFragment;
    "getHorizontalMovement(uint8,uint8)": FunctionFragment;
    "getInBetweenMask(uint8,uint8)": FunctionFragment;
    "getLegalMoves()": FunctionFragment;
    "getPositionMask(uint8)": FunctionFragment;
    "getVerticalMovement(uint8,uint8)": FunctionFragment;
    "initializeGame()": FunctionFragment;
    "moveIndex()": FunctionFragment;
    "owner()": FunctionFragment;
    "pieceAtPosition(uint256,uint8)": FunctionFragment;
    "pieceUnderAttack(uint256,uint8)": FunctionFragment;
    "playMove(uint16)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "searchPiece(uint256,uint32,uint32,uint16,uint16)": FunctionFragment;
    "setBetting(address)": FunctionFragment;
    "setPosition(uint256,uint8,uint8)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "validMovesInit(uint256)": FunctionFragment;
    "verifyExecuteBishopMove(uint256,uint8,uint8)": FunctionFragment;
    "verifyExecuteKingMove(uint256,uint8,uint8,uint32)": FunctionFragment;
    "verifyExecuteKnightMove(uint256,uint8,uint8)": FunctionFragment;
    "verifyExecutePawnMove(uint256,uint16,uint32,uint32)": FunctionFragment;
    "verifyExecuteQueenMove(uint256,uint8,uint8)": FunctionFragment;
    "verifyExecuteRookMove(uint256,uint8,uint8)": FunctionFragment;
    "whiteState()": FunctionFragment;
    "zeroPosition(uint256,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "betting"
      | "blackState"
      | "boardState"
      | "checkBishopValidMoves"
      | "checkEndgame"
      | "checkForCheck"
      | "checkKingValidMoves"
      | "checkKnightValidMoves"
      | "checkMove"
      | "checkPawnValidMoves"
      | "checkQueenValidMoves"
      | "checkRookValidMoves"
      | "commitMove"
      | "convertToCircuit"
      | "currentTurnBlack"
      | "gameIndex"
      | "gameStateLists"
      | "getChessGameState"
      | "getHorizontalMovement"
      | "getInBetweenMask"
      | "getLegalMoves"
      | "getPositionMask"
      | "getVerticalMovement"
      | "initializeGame"
      | "moveIndex"
      | "owner"
      | "pieceAtPosition"
      | "pieceUnderAttack"
      | "playMove"
      | "renounceOwnership"
      | "searchPiece"
      | "setBetting"
      | "setPosition"
      | "transferOwnership"
      | "validMovesInit"
      | "verifyExecuteBishopMove"
      | "verifyExecuteKingMove"
      | "verifyExecuteKnightMove"
      | "verifyExecutePawnMove"
      | "verifyExecuteQueenMove"
      | "verifyExecuteRookMove"
      | "whiteState"
      | "zeroPosition"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "betting", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blackState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boardState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkBishopValidMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkEndgame",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkForCheck",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkKingValidMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkKnightValidMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMove",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkPawnValidMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkQueenValidMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRookValidMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "commitMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToCircuit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTurnBlack",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gameIndex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gameStateLists",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChessGameState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHorizontalMovement",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInBetweenMask",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLegalMoves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionMask",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerticalMovement",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeGame",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "moveIndex", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pieceAtPosition",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "pieceUnderAttack",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "playMove",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "searchPiece",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBetting",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPosition",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validMovesInit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExecuteBishopMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExecuteKingMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExecuteKnightMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExecutePawnMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExecuteQueenMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExecuteRookMove",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "zeroPosition",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "betting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blackState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boardState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkBishopValidMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEndgame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkForCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkKingValidMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkKnightValidMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkPawnValidMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkQueenValidMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkRookValidMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertToCircuit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTurnBlack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gameStateLists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChessGameState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHorizontalMovement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInBetweenMask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLegalMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionMask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerticalMovement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moveIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pieceAtPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pieceUnderAttack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "searchPiece",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBetting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validMovesInit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExecuteBishopMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExecuteKingMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExecuteKnightMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExecutePawnMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExecuteQueenMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExecuteRookMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whiteState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zeroPosition",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "check()": EventFragment;
    "movePlayed(uint256,uint32,uint32,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "check"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "movePlayed"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface checkEventObject {}
export type checkEvent = TypedEvent<[], checkEventObject>;

export type checkEventFilter = TypedEventFilter<checkEvent>;

export interface movePlayedEventObject {
  gameState: BigNumber;
  leela_state: number;
  world_state: number;
  leelaMove: boolean;
}
export type movePlayedEvent = TypedEvent<
  [BigNumber, number, number, boolean],
  movePlayedEventObject
>;

export type movePlayedEventFilter = TypedEventFilter<movePlayedEvent>;

export interface Chess extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ChessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    betting(overrides?: CallOverrides): Promise<[string]>;

    blackState(overrides?: CallOverrides): Promise<[number]>;

    boardState(overrides?: CallOverrides): Promise<[BigNumber]>;

    checkBishopValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkEndgame(overrides?: CallOverrides): Promise<[number]>;

    checkForCheck(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    checkKingValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkKnightValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    checkPawnValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkQueenValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkRookValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    commitMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { newGameState: BigNumber }>;

    convertToCircuit(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    currentTurnBlack(overrides?: CallOverrides): Promise<[boolean]>;

    gameIndex(overrides?: CallOverrides): Promise<[number]>;

    gameStateLists(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getChessGameState(
      overrides?: CallOverrides
    ): Promise<[BigNumber, number, number, boolean, number, number]>;

    getHorizontalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getInBetweenMask(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLegalMoves(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPositionMask(
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVerticalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    initializeGame(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    moveIndex(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pieceAtPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    pieceUnderAttack(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    playMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    searchPiece(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      pBitOffset: PromiseOrValue<BigNumberish>,
      bitSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setBetting(
      _betting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      piece: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validMovesInit(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    verifyExecuteBishopMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verifyExecuteKingMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & { newGameState: BigNumber; newPlayerState: number }
    >;

    verifyExecuteKnightMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verifyExecutePawnMove(
      gameState: PromiseOrValue<BigNumberish>,
      move: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & { newGameState: BigNumber; newPlayerState: number }
    >;

    verifyExecuteQueenMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verifyExecuteRookMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    whiteState(overrides?: CallOverrides): Promise<[number]>;

    zeroPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  betting(overrides?: CallOverrides): Promise<string>;

  blackState(overrides?: CallOverrides): Promise<number>;

  boardState(overrides?: CallOverrides): Promise<BigNumber>;

  checkBishopValidMoves(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, number[], number]>;

  checkEndgame(overrides?: CallOverrides): Promise<number>;

  checkForCheck(
    gameState: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkKingValidMoves(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, number[], number]>;

  checkKnightValidMoves(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, number[], number]>;

  checkMove(
    move: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkPawnValidMoves(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    opponentState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, number[], number]>;

  checkQueenValidMoves(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, number[], number]>;

  checkRookValidMoves(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, number[], number]>;

  commitMove(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertToCircuit(overrides?: CallOverrides): Promise<BigNumber[]>;

  currentTurnBlack(overrides?: CallOverrides): Promise<boolean>;

  gameIndex(overrides?: CallOverrides): Promise<number>;

  gameStateLists(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getChessGameState(
    overrides?: CallOverrides
  ): Promise<[BigNumber, number, number, boolean, number, number]>;

  getHorizontalMovement(
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  getInBetweenMask(
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLegalMoves(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPositionMask(
    pos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVerticalMovement(
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  initializeGame(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  moveIndex(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  pieceAtPosition(
    gameState: PromiseOrValue<BigNumberish>,
    pos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  pieceUnderAttack(
    gameState: PromiseOrValue<BigNumberish>,
    pos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  playMove(
    move: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  searchPiece(
    gameState: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    opponentState: PromiseOrValue<BigNumberish>,
    pBitOffset: PromiseOrValue<BigNumberish>,
    bitSize: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setBetting(
    _betting: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPosition(
    gameState: PromiseOrValue<BigNumberish>,
    pos: PromiseOrValue<BigNumberish>,
    piece: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validMovesInit(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  verifyExecuteBishopMove(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verifyExecuteKingMove(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number] & { newGameState: BigNumber; newPlayerState: number }
  >;

  verifyExecuteKnightMove(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verifyExecutePawnMove(
    gameState: PromiseOrValue<BigNumberish>,
    move: PromiseOrValue<BigNumberish>,
    playerState: PromiseOrValue<BigNumberish>,
    opponentState: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number] & { newGameState: BigNumber; newPlayerState: number }
  >;

  verifyExecuteQueenMove(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verifyExecuteRookMove(
    gameState: PromiseOrValue<BigNumberish>,
    fromPos: PromiseOrValue<BigNumberish>,
    toPos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  whiteState(overrides?: CallOverrides): Promise<number>;

  zeroPosition(
    gameState: PromiseOrValue<BigNumberish>,
    pos: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    betting(overrides?: CallOverrides): Promise<string>;

    blackState(overrides?: CallOverrides): Promise<number>;

    boardState(overrides?: CallOverrides): Promise<BigNumber>;

    checkBishopValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkEndgame(overrides?: CallOverrides): Promise<number>;

    checkForCheck(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkKingValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkKnightValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkPawnValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkQueenValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    checkRookValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, number[], number]>;

    commitMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertToCircuit(overrides?: CallOverrides): Promise<BigNumber[]>;

    currentTurnBlack(overrides?: CallOverrides): Promise<boolean>;

    gameIndex(overrides?: CallOverrides): Promise<number>;

    gameStateLists(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChessGameState(
      overrides?: CallOverrides
    ): Promise<[BigNumber, number, number, boolean, number, number]>;

    getHorizontalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    getInBetweenMask(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLegalMoves(overrides?: CallOverrides): Promise<number[]>;

    getPositionMask(
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVerticalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    initializeGame(overrides?: CallOverrides): Promise<void>;

    moveIndex(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    pieceAtPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    pieceUnderAttack(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    playMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    searchPiece(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      pBitOffset: PromiseOrValue<BigNumberish>,
      bitSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setBetting(
      _betting: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      piece: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    validMovesInit(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    verifyExecuteBishopMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteKingMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & { newGameState: BigNumber; newPlayerState: number }
    >;

    verifyExecuteKnightMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecutePawnMove(
      gameState: PromiseOrValue<BigNumberish>,
      move: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & { newGameState: BigNumber; newPlayerState: number }
    >;

    verifyExecuteQueenMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteRookMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whiteState(overrides?: CallOverrides): Promise<number>;

    zeroPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "check()"(): checkEventFilter;
    check(): checkEventFilter;

    "movePlayed(uint256,uint32,uint32,bool)"(
      gameState?: null,
      leela_state?: null,
      world_state?: null,
      leelaMove?: null
    ): movePlayedEventFilter;
    movePlayed(
      gameState?: null,
      leela_state?: null,
      world_state?: null,
      leelaMove?: null
    ): movePlayedEventFilter;
  };

  estimateGas: {
    betting(overrides?: CallOverrides): Promise<BigNumber>;

    blackState(overrides?: CallOverrides): Promise<BigNumber>;

    boardState(overrides?: CallOverrides): Promise<BigNumber>;

    checkBishopValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkEndgame(overrides?: CallOverrides): Promise<BigNumber>;

    checkForCheck(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkKingValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkKnightValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkPawnValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkQueenValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkRookValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commitMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertToCircuit(overrides?: CallOverrides): Promise<BigNumber>;

    currentTurnBlack(overrides?: CallOverrides): Promise<BigNumber>;

    gameIndex(overrides?: CallOverrides): Promise<BigNumber>;

    gameStateLists(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChessGameState(overrides?: CallOverrides): Promise<BigNumber>;

    getHorizontalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInBetweenMask(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLegalMoves(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPositionMask(
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVerticalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeGame(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    moveIndex(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pieceAtPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pieceUnderAttack(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    playMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    searchPiece(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      pBitOffset: PromiseOrValue<BigNumberish>,
      bitSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBetting(
      _betting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      piece: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validMovesInit(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteBishopMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteKingMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteKnightMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecutePawnMove(
      gameState: PromiseOrValue<BigNumberish>,
      move: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteQueenMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyExecuteRookMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whiteState(overrides?: CallOverrides): Promise<BigNumber>;

    zeroPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    betting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blackState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    boardState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkBishopValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkEndgame(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkForCheck(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkKingValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkKnightValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkPawnValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkQueenValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkRookValidMoves(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    commitMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertToCircuit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentTurnBlack(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gameIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gameStateLists(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChessGameState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHorizontalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInBetweenMask(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLegalMoves(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPositionMask(
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVerticalMovement(
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeGame(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    moveIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pieceAtPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pieceUnderAttack(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    playMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    searchPiece(
      gameState: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      pBitOffset: PromiseOrValue<BigNumberish>,
      bitSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBetting(
      _betting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      piece: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validMovesInit(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyExecuteBishopMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyExecuteKingMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyExecuteKnightMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyExecutePawnMove(
      gameState: PromiseOrValue<BigNumberish>,
      move: PromiseOrValue<BigNumberish>,
      playerState: PromiseOrValue<BigNumberish>,
      opponentState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyExecuteQueenMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyExecuteRookMove(
      gameState: PromiseOrValue<BigNumberish>,
      fromPos: PromiseOrValue<BigNumberish>,
      toPos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whiteState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    zeroPosition(
      gameState: PromiseOrValue<BigNumberish>,
      pos: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
