/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Betting__factory } from "./Betting__factory";
export { Chess__factory } from "./Chess__factory";
export { Leela__factory } from "./Leela__factory";
