/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface BettingGameInterface extends utils.Interface {
  functions: {
    "accountsPayable(address)": FunctionFragment;
    "addStake(bool)": FunctionFragment;
    "callTimerOver()": FunctionFragment;
    "chess()": FunctionFragment;
    "claimPayout()": FunctionFragment;
    "gameIndex()": FunctionFragment;
    "getCurMovesAndVotes()": FunctionFragment;
    "getFrontEndPoolState()": FunctionFragment;
    "getTimeLeft()": FunctionFragment;
    "getUserStakeState(address)": FunctionFragment;
    "getWorldMove()": FunctionFragment;
    "giveLeelaLegalMoves()": FunctionFragment;
    "initialize(address,address,uint256)": FunctionFragment;
    "leela()": FunctionFragment;
    "leelaColor()": FunctionFragment;
    "leelaHashInputs()": FunctionFragment;
    "leelaMove()": FunctionFragment;
    "leelaPoolSize()": FunctionFragment;
    "leelaStakes(uint16,address)": FunctionFragment;
    "leelaTurn()": FunctionFragment;
    "makeLeelaMove(bytes,bytes)": FunctionFragment;
    "manualLeelaMove(uint16)": FunctionFragment;
    "minStake()": FunctionFragment;
    "moveIndex()": FunctionFragment;
    "moveStakeToNextGame()": FunctionFragment;
    "owner()": FunctionFragment;
    "registeredMoves(uint16,uint16,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setChess(address)": FunctionFragment;
    "setLeela(address)": FunctionFragment;
    "setMinStake(uint256)": FunctionFragment;
    "setPoolSize(uint256)": FunctionFragment;
    "setVotePeriod(uint256)": FunctionFragment;
    "startVoteTimer()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userVotedMove()": FunctionFragment;
    "votePeriodDuration()": FunctionFragment;
    "votePeriodEnd()": FunctionFragment;
    "voteWorldMove(uint16)": FunctionFragment;
    "voters(uint16,uint16,address)": FunctionFragment;
    "worldPoolSize()": FunctionFragment;
    "worldStakes(uint16,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accountsPayable"
      | "addStake"
      | "callTimerOver"
      | "chess"
      | "claimPayout"
      | "gameIndex"
      | "getCurMovesAndVotes"
      | "getFrontEndPoolState"
      | "getTimeLeft"
      | "getUserStakeState"
      | "getWorldMove"
      | "giveLeelaLegalMoves"
      | "initialize"
      | "leela"
      | "leelaColor"
      | "leelaHashInputs"
      | "leelaMove"
      | "leelaPoolSize"
      | "leelaStakes"
      | "leelaTurn"
      | "makeLeelaMove"
      | "manualLeelaMove"
      | "minStake"
      | "moveIndex"
      | "moveStakeToNextGame"
      | "owner"
      | "registeredMoves"
      | "renounceOwnership"
      | "setChess"
      | "setLeela"
      | "setMinStake"
      | "setPoolSize"
      | "setVotePeriod"
      | "startVoteTimer"
      | "transferOwnership"
      | "userVotedMove"
      | "votePeriodDuration"
      | "votePeriodEnd"
      | "voteWorldMove"
      | "voters"
      | "worldPoolSize"
      | "worldStakes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountsPayable",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addStake",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "callTimerOver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "chess", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimPayout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gameIndex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurMovesAndVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFrontEndPoolState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeLeft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakeState",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorldMove",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "giveLeelaLegalMoves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "leela", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "leelaColor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leelaHashInputs",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "leelaMove", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "leelaPoolSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leelaStakes",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "leelaTurn", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "makeLeelaMove",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "manualLeelaMove",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "moveIndex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "moveStakeToNextGame",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registeredMoves",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChess",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLeela",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinStake",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolSize",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotePeriod",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "startVoteTimer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "userVotedMove",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votePeriodDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votePeriodEnd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteWorldMove",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "voters",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "worldPoolSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "worldStakes",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountsPayable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callTimerOver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurMovesAndVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFrontEndPoolState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakeState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorldMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "giveLeelaLegalMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leela", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leelaColor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leelaHashInputs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leelaMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leelaPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leelaStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leelaTurn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeLeelaMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualLeelaMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "moveIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "moveStakeToNextGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registeredMoves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setChess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setLeela", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startVoteTimer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVotedMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePeriodDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePeriodEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteWorldMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "worldPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "worldStakes",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "gameEnd(bool)": EventFragment;
    "gameStart(bool)": EventFragment;
    "leelaMovePlayed(uint16)": EventFragment;
    "stakeMade(address,uint256,bool)": EventFragment;
    "voteMade(address,uint256,uint16)": EventFragment;
    "worldMovePlayed(uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "gameEnd"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "gameStart"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "leelaMovePlayed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "stakeMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "voteMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "worldMovePlayed"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface gameEndEventObject {
  leelaWon: boolean;
}
export type gameEndEvent = TypedEvent<[boolean], gameEndEventObject>;

export type gameEndEventFilter = TypedEventFilter<gameEndEvent>;

export interface gameStartEventObject {
  leelaColor: boolean;
}
export type gameStartEvent = TypedEvent<[boolean], gameStartEventObject>;

export type gameStartEventFilter = TypedEventFilter<gameStartEvent>;

export interface leelaMovePlayedEventObject {
  leelaMove: number;
}
export type leelaMovePlayedEvent = TypedEvent<
  [number],
  leelaMovePlayedEventObject
>;

export type leelaMovePlayedEventFilter = TypedEventFilter<leelaMovePlayedEvent>;

export interface stakeMadeEventObject {
  player: string;
  amt: BigNumber;
  leelaSide: boolean;
}
export type stakeMadeEvent = TypedEvent<
  [string, BigNumber, boolean],
  stakeMadeEventObject
>;

export type stakeMadeEventFilter = TypedEventFilter<stakeMadeEvent>;

export interface voteMadeEventObject {
  player: string;
  power: BigNumber;
  move: number;
}
export type voteMadeEvent = TypedEvent<
  [string, BigNumber, number],
  voteMadeEventObject
>;

export type voteMadeEventFilter = TypedEventFilter<voteMadeEvent>;

export interface worldMovePlayedEventObject {
  worldMove: number;
}
export type worldMovePlayedEvent = TypedEvent<
  [number],
  worldMovePlayedEventObject
>;

export type worldMovePlayedEventFilter = TypedEventFilter<worldMovePlayedEvent>;

export interface BettingGame extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BettingGameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountsPayable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    addStake(
      leelaSide: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callTimerOver(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    chess(overrides?: CallOverrides): Promise<[string]>;

    claimPayout(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    gameIndex(overrides?: CallOverrides): Promise<[number]>;

    getCurMovesAndVotes(
      overrides?: CallOverrides
    ): Promise<[number[], BigNumber[]]>;

    getFrontEndPoolState(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getTimeLeft(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserStakeState(
      userAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getWorldMove(overrides?: CallOverrides): Promise<[number]>;

    giveLeelaLegalMoves(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _chess: PromiseOrValue<string>,
      _leela: PromiseOrValue<string>,
      initialPoolSize: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    leela(overrides?: CallOverrides): Promise<[string]>;

    leelaColor(overrides?: CallOverrides): Promise<[boolean]>;

    leelaHashInputs(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    leelaMove(overrides?: CallOverrides): Promise<[number]>;

    leelaPoolSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    leelaStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    leelaTurn(overrides?: CallOverrides): Promise<[boolean]>;

    makeLeelaMove(
      proof: PromiseOrValue<BytesLike>,
      instances: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    manualLeelaMove(
      manualMove: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    minStake(overrides?: CallOverrides): Promise<[BigNumber]>;

    moveIndex(overrides?: CallOverrides): Promise<[number]>;

    moveStakeToNextGame(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registeredMoves(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setChess(
      _chess: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLeela(
      _leela: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinStake(
      _minStake: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPoolSize(
      _a: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setVotePeriod(
      d: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startVoteTimer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userVotedMove(overrides?: CallOverrides): Promise<[number]>;

    votePeriodDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    votePeriodEnd(overrides?: CallOverrides): Promise<[BigNumber]>;

    voteWorldMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voters(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    worldPoolSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    worldStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  accountsPayable(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  addStake(
    leelaSide: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callTimerOver(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  chess(overrides?: CallOverrides): Promise<string>;

  claimPayout(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  gameIndex(overrides?: CallOverrides): Promise<number>;

  getCurMovesAndVotes(
    overrides?: CallOverrides
  ): Promise<[number[], BigNumber[]]>;

  getFrontEndPoolState(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  getTimeLeft(overrides?: CallOverrides): Promise<BigNumber>;

  getUserStakeState(
    userAddr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getWorldMove(overrides?: CallOverrides): Promise<number>;

  giveLeelaLegalMoves(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _chess: PromiseOrValue<string>,
    _leela: PromiseOrValue<string>,
    initialPoolSize: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  leela(overrides?: CallOverrides): Promise<string>;

  leelaColor(overrides?: CallOverrides): Promise<boolean>;

  leelaHashInputs(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  leelaMove(overrides?: CallOverrides): Promise<number>;

  leelaPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

  leelaStakes(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  leelaTurn(overrides?: CallOverrides): Promise<boolean>;

  makeLeelaMove(
    proof: PromiseOrValue<BytesLike>,
    instances: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  manualLeelaMove(
    manualMove: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  minStake(overrides?: CallOverrides): Promise<BigNumber>;

  moveIndex(overrides?: CallOverrides): Promise<number>;

  moveStakeToNextGame(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  registeredMoves(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setChess(
    _chess: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLeela(
    _leela: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinStake(
    _minStake: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPoolSize(
    _a: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setVotePeriod(
    d: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startVoteTimer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userVotedMove(overrides?: CallOverrides): Promise<number>;

  votePeriodDuration(overrides?: CallOverrides): Promise<BigNumber>;

  votePeriodEnd(overrides?: CallOverrides): Promise<BigNumber>;

  voteWorldMove(
    move: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voters(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  worldPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

  worldStakes(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    accountsPayable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addStake(
      leelaSide: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    callTimerOver(overrides?: CallOverrides): Promise<void>;

    chess(overrides?: CallOverrides): Promise<string>;

    claimPayout(overrides?: CallOverrides): Promise<void>;

    gameIndex(overrides?: CallOverrides): Promise<number>;

    getCurMovesAndVotes(
      overrides?: CallOverrides
    ): Promise<[number[], BigNumber[]]>;

    getFrontEndPoolState(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getTimeLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getUserStakeState(
      userAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getWorldMove(overrides?: CallOverrides): Promise<number>;

    giveLeelaLegalMoves(overrides?: CallOverrides): Promise<void>;

    initialize(
      _chess: PromiseOrValue<string>,
      _leela: PromiseOrValue<string>,
      initialPoolSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    leela(overrides?: CallOverrides): Promise<string>;

    leelaColor(overrides?: CallOverrides): Promise<boolean>;

    leelaHashInputs(overrides?: CallOverrides): Promise<void>;

    leelaMove(overrides?: CallOverrides): Promise<number>;

    leelaPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

    leelaStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    leelaTurn(overrides?: CallOverrides): Promise<boolean>;

    makeLeelaMove(
      proof: PromiseOrValue<BytesLike>,
      instances: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    manualLeelaMove(
      manualMove: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    minStake(overrides?: CallOverrides): Promise<BigNumber>;

    moveIndex(overrides?: CallOverrides): Promise<number>;

    moveStakeToNextGame(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    registeredMoves(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setChess(
      _chess: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLeela(
      _leela: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinStake(
      _minStake: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPoolSize(
      _a: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setVotePeriod(
      d: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    startVoteTimer(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    userVotedMove(overrides?: CallOverrides): Promise<number>;

    votePeriodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    votePeriodEnd(overrides?: CallOverrides): Promise<BigNumber>;

    voteWorldMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    voters(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    worldPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

    worldStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "gameEnd(bool)"(leelaWon?: null): gameEndEventFilter;
    gameEnd(leelaWon?: null): gameEndEventFilter;

    "gameStart(bool)"(leelaColor?: null): gameStartEventFilter;
    gameStart(leelaColor?: null): gameStartEventFilter;

    "leelaMovePlayed(uint16)"(leelaMove?: null): leelaMovePlayedEventFilter;
    leelaMovePlayed(leelaMove?: null): leelaMovePlayedEventFilter;

    "stakeMade(address,uint256,bool)"(
      player?: null,
      amt?: null,
      leelaSide?: null
    ): stakeMadeEventFilter;
    stakeMade(
      player?: null,
      amt?: null,
      leelaSide?: null
    ): stakeMadeEventFilter;

    "voteMade(address,uint256,uint16)"(
      player?: null,
      power?: null,
      move?: null
    ): voteMadeEventFilter;
    voteMade(player?: null, power?: null, move?: null): voteMadeEventFilter;

    "worldMovePlayed(uint16)"(worldMove?: null): worldMovePlayedEventFilter;
    worldMovePlayed(worldMove?: null): worldMovePlayedEventFilter;
  };

  estimateGas: {
    accountsPayable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addStake(
      leelaSide: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callTimerOver(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    chess(overrides?: CallOverrides): Promise<BigNumber>;

    claimPayout(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    gameIndex(overrides?: CallOverrides): Promise<BigNumber>;

    getCurMovesAndVotes(overrides?: CallOverrides): Promise<BigNumber>;

    getFrontEndPoolState(overrides?: CallOverrides): Promise<BigNumber>;

    getTimeLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getUserStakeState(
      userAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWorldMove(overrides?: CallOverrides): Promise<BigNumber>;

    giveLeelaLegalMoves(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      _chess: PromiseOrValue<string>,
      _leela: PromiseOrValue<string>,
      initialPoolSize: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    leela(overrides?: CallOverrides): Promise<BigNumber>;

    leelaColor(overrides?: CallOverrides): Promise<BigNumber>;

    leelaHashInputs(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    leelaMove(overrides?: CallOverrides): Promise<BigNumber>;

    leelaPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

    leelaStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    leelaTurn(overrides?: CallOverrides): Promise<BigNumber>;

    makeLeelaMove(
      proof: PromiseOrValue<BytesLike>,
      instances: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    manualLeelaMove(
      manualMove: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    minStake(overrides?: CallOverrides): Promise<BigNumber>;

    moveIndex(overrides?: CallOverrides): Promise<BigNumber>;

    moveStakeToNextGame(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registeredMoves(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setChess(
      _chess: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLeela(
      _leela: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinStake(
      _minStake: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPoolSize(
      _a: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setVotePeriod(
      d: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startVoteTimer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userVotedMove(overrides?: CallOverrides): Promise<BigNumber>;

    votePeriodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    votePeriodEnd(overrides?: CallOverrides): Promise<BigNumber>;

    voteWorldMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voters(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    worldPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

    worldStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountsPayable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addStake(
      leelaSide: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callTimerOver(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    chess(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimPayout(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    gameIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurMovesAndVotes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFrontEndPoolState(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTimeLeft(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserStakeState(
      userAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWorldMove(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    giveLeelaLegalMoves(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _chess: PromiseOrValue<string>,
      _leela: PromiseOrValue<string>,
      initialPoolSize: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    leela(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    leelaColor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    leelaHashInputs(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    leelaMove(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    leelaPoolSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    leelaStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    leelaTurn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeLeelaMove(
      proof: PromiseOrValue<BytesLike>,
      instances: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    manualLeelaMove(
      manualMove: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    minStake(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    moveIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    moveStakeToNextGame(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registeredMoves(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setChess(
      _chess: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLeela(
      _leela: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinStake(
      _minStake: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPoolSize(
      _a: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setVotePeriod(
      d: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startVoteTimer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userVotedMove(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    votePeriodDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votePeriodEnd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    voteWorldMove(
      move: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voters(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    worldPoolSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    worldStakes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
